modLoader="javafml" #mandatory

loaderVersion="[2,]" #mandatory

license="MIT"

issueTrackerURL="https://discord.gg/WsuFsGSegD" #optional

[[mods]] #mandatory
modId="selling_bin"
version="${mod_version}"
displayName="${mod_name}"
displayURL="http://curseforge.com/minecraft/mc-mods/wds-selling-bin"
logoFile = "icon.png"
mod_authors="${mod_authors}" #optional
description='''A data-driven Selling Bin mod

Credits:
wdiscute - Main Developer
DayTheMagpie - Selling Bin UI Art
Redeix - Selling Bin model
Nikdo53 - Tiny Multiblock Lib
'''

[[dependencies.selling_bin]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="AFTER"
side="BOTH"

# Here's another dependency
[[dependencies.selling_bin]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"
